site_name: Drupal Contacts
site_description: Project documentation.
site_author: yanniboi <Yan Loetzer>

repo_url: https://github.com/freelygive/decoupled_auth/
theme: spacelab
#theme_dir: yanniboi_spacelab
pages:
- Home: 'index.md'
- Contact: 'contact.md'
- Drupal 8:
    - 'Decoupled User Authentication': 'drupal-8/decoupled_auth.md'
    - 'Contacts': 'drupal-8/contacts.md'
- Contribute:
    - 'Where to start': 'development/where-to-start.md'
    - 'Development Automation': 'development/automation.md'
- Drupal 7: 'drupal-7/about.md'


copyright: Copyright &copy; 2016 <a href="https://twitter.com/yanniboi">yanniboi</a>.